// --- Begin Copyright Block -----[ do not move or remove ]------
// Copyright (c) 2019, Cadence Design Systems, Inc. All rights reserved.

// The model contained herein is the proprietary and confidential information 
// of Cadence, and is supplied subject to, and may be used only by Cadences 
// customer in accordance with a previously executed license and maintenance 
// agreement between Cadence and that customer. This model is intended for use 
// with products only from Cadence Design Systems, Inc.  The use or sharing of 
// any models from this library or any of its modified/extended form is 
// strictly prohibited with any non-Cadence products.

// ALL MATERIALS FURNISHED BY CADENCE HEREUNDER ARE PROVIDED "AS IS" WITHOUT 
// WARRANTY OF ANY KIND, AND CADENCE SPECIFICALLY DISCLAIMS ANY WARRANTY OF 
// NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE OR MERCHANTABILITY. 
// CADENCE SHALL NOT BE LIABLE FOR ANY COSTS OF PROCUREMENT OF SUBSTITUTES, 
// LOSS OF PROFITS, INTERRUPTION OF BUSINESS, OR FOR ANY OTHER SPECIAL, 
// CONSEQUENTIAL OR INCIDENTAL DAMAGES, HOWEVER CAUSED, WHETHER FOR BREACH OF 
// WARRANTY, CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE.
/* --- End Copyright Block -------------------------------------- */
////////////////////////////////////////////////////////////////////////
// PLEASE DO NOT EDIT THIS FILE.                                                           
// 
// structural netlist for SAR ADC
////////////////////////////////////////////////////////////////////////

// Library - rxbb_virtuoso, Cell - ADC_8bit, View - schematic
// LAST TIME SAVED: Jun  3 08:14:36 2019
// NETLIST TIME: Jun  3 14:24:25 2019

`timescale 1s / 1ps 

`view sch
module ADC_8bit import cds_rnm_pkg::*; import EE_pkg::*; (outClkI, outClkQ, outi, outq, ADCEn, .VCM(vcm), VDD, 
    VREF1, VREF2, VSS, Vinm, Vinp, clkn, clkp, fclkn, fclkp);

output logic outClkI, outClkQ;

input logic ADCEn, clkn, clkp, fclkn, fclkp;
input EEnet VDD, VSS;
input wreal4state VREF1, VREF2, vcm;

output [7:0]  outq;
output [7:0]  outi;

input wreal4state Vinp [1:0];
input wreal4state Vinm [1:0];

// Buses in the design

wire  [7:0]  dacIn;

// wreals in the design
wreal4state sampleP, sampleN, dacP, dacN;

sarDAC IDAC ( .vcm(vcm), .vref1(VREF1), .vdd(VDD), .vss(VSS), 
    .outn(dacN), .outp(dacP), .en(ADCEn), .in(dacIn), .vref2(VREF2));

sarLogic ILOGIC ( .muxClkn(muxClkn), .muxClkp(muxClkp), 
    .outClkI(outClkI), .outClkQ(outClkQ), .cClkn(cClkn), .cClkp(cClkp), 
    .vdd(VDD), .vss(VSS), .dacIn(dacIn), .outI(outi), .outQ(outq), 
    .compOutN(compOutN), .compOutP(compOutP), .en(ADCEn), 
    .fClkN(fclkn), .fClkP(fclkp), .sampleClkN(clkn), 
    .sampleClkP(clkp));

sarSamplingMux IMUX ( .vdd(VDD), .vss(VSS), .outm(sampleN), 
    .outp(sampleP), .clkm(muxClkn), .clkp(muxClkp), .en(ADCEn), 
    .iinm(Vinm[0]), .iinp(Vinp[0]), .qinm(Vinm[1]), .qinp(Vinp[1]), 
    .vcm(vcm));

sarComparator ICMPM ( .clkn(cClkn), .clkp(cClkp), .vdd(VDD), .vss(VSS), 
    .out(compOutN), .en(ADCEn), .inm(sampleN), .inp(dacN));

sarComparator ICMPP ( .clkn(cClkn), .clkp(cClkp), .vdd(VDD), .vss(VSS), 
    .out(compOutP), .en(ADCEn), .inm(dacP), .inp(sampleP));

endmodule
