// --- Begin Copyright Block -----[ do not move or remove ]------
// Copyright (c) 2019, Cadence Design Systems, Inc. All rights reserved.

// The model contained herein is the proprietary and confidential information 
// of Cadence, and is supplied subject to, and may be used only by Cadences 
// customer in accordance with a previously executed license and maintenance 
// agreement between Cadence and that customer. This model is intended for use 
// with products only from Cadence Design Systems, Inc.  The use or sharing of 
// any models from this library or any of its modified/extended form is 
// strictly prohibited with any non-Cadence products.

// ALL MATERIALS FURNISHED BY CADENCE HEREUNDER ARE PROVIDED "AS IS" WITHOUT 
// WARRANTY OF ANY KIND, AND CADENCE SPECIFICALLY DISCLAIMS ANY WARRANTY OF 
// NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE OR MERCHANTABILITY. 
// CADENCE SHALL NOT BE LIABLE FOR ANY COSTS OF PROCUREMENT OF SUBSTITUTES, 
// LOSS OF PROFITS, INTERRUPTION OF BUSINESS, OR FOR ANY OTHER SPECIAL, 
// CONSEQUENTIAL OR INCIDENTAL DAMAGES, HOWEVER CAUSED, WHETHER FOR BREACH OF 
// WARRANTY, CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE.
/* --- End Copyright Block -------------------------------------- */
////////////////////////////////////////////////////////////////////////
// PLEASE DO NOT EDIT THIS FILE.                                                           
// 
// rxbb simulation testbench
//
////////////////////////////////////////////////////////////////////////

// Library - rxbb_virtuoso, Cell - rxBB_sim, View - schematic
// LAST TIME SAVED: Jun  3 09:06:17 2019
// NETLIST TIME: Jun  3 10:47:33 2019

`timescale 1s/1ps
import cds_rnm_pkg::*;
import EE_pkg::*;

module rxBB_sim ();

// Buses in the design

wire  [7:0]  dcocq;

wire  [7:0]  dcoci;

wire  [3:0]  refTrim2;

wire  [3:0]  refTrim1;

wire  [3:0]  gain;

wire  [3:0]  bwTrim;

wire  [7:0]  outq;

wire  [7:0]  outi;

// EEnets in testbench
EEnet vdd,vss;

//wreals in testbench
wreal4state vref, inim, inip, inqm, inqp;


rxBB_stimulus ISTIMULUS ( .refEn(adcRefEn), .fastClkn(fastClkn), 
    .fastClkp(fastClkp), .sampleClkn(sampleClkn), 
    .sampleClkp(sampleClkp), .outClki(outClkI), .outClkq(outClkQ), 
    .vss(vss), .vdd(vdd), .dcoci(dcoci), .dcocq(dcocq), .vref(vref), 
    .bwTrim(bwTrim), .en(en), .gain(gain), .inim(inim), .inip(inip), 
    .inqm(inqm), .inqp(inqp), .refTrim1(refTrim1), .refTrim2(refTrim2), 
    .outi(outi), .outq(outq));

rxBB IrxBB ( .outClkI(outClkI), .outClkQ(outClkQ), .adcRefEn(adcRefEn), 
    .fClkn(fastClkn), .fClkp(fastClkp), .dcoci(dcoci[7:0]), 
    .dcocq(dcocq[7:0]), .vref(vref), .clkn(sampleClkn), 
    .gain(gain[3:0]), .bwTrim(bwTrim[3:0]), .en(en), .clkp(sampleClkp), 
    .refTrim2(refTrim2[3:0]), .refTrim1(refTrim1[3:0]), .vss(vss), 
    .vdd(vdd), .outi(outi[7:0]), .outq(outq[7:0]), .inim(inim), 
    .inip(inip), .inqm(inqm), .inqp(inqp));

endmodule
