/* --- Begin Copyright Block -----[ do not move or remove ]------ */
// Copyright (c) 2019, Cadence Design Systems, Inc. All rights reserved.

// The model contained herein is the proprietary and confidential information 
// of Cadence, and is supplied subject to, and may be used only by Cadences 
// customer in accordance with a previously executed license and maintenance 
// agreement between Cadence and that customer. This model is intended for use 
// with products only from Cadence Design Systems, Inc.  The use or sharing of 
// any models from this library or any of its modified/extended form is 
// strictly prohibited with any non-Cadence products.

// ALL MATERIALS FURNISHED BY CADENCE HEREUNDER ARE PROVIDED "AS IS" WITHOUT 
// WARRANTY OF ANY KIND, AND CADENCE SPECIFICALLY DISCLAIMS ANY WARRANTY OF 
// NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE OR MERCHANTABILITY. 
// CADENCE SHALL NOT BE LIABLE FOR ANY COSTS OF PROCUREMENT OF SUBSTITUTES, 
// LOSS OF PROFITS, INTERRUPTION OF BUSINESS, OR FOR ANY OTHER SPECIAL, 
// CONSEQUENTIAL OR INCIDENTAL DAMAGES, HOWEVER CAUSED, WHETHER FOR BREACH OF 
// WARRANTY, CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE.
/* --- End Copyright Block -------------------------------------- */
////////////////////////////////////////////////////////////////////////
// PLEASE DO NOT EDIT THIS FILE.                                                           
// 
// rxbb top-level structural
////////////////////////////////////////////////////////////////////////

// AMS netlist generated by the AMS Unified netlister
// IC subversion:  IC6.1.7-64b.500.23 
// Xcelium version: 18.09-s013
// Copyright(C) 2005-2009, Cadence Design Systems, Inc
// Design library name: rxbb_virtuoso
// Design cell name: rxBB

// Library - rxbb_virtuoso, Cell - rxBB, View - schematic
// LAST TIME SAVED: Jun  3 08:17:34 2019
// NETLIST TIME: Jun  3 10:47:33 2019

module rxBB import cds_rnm_pkg::*; import EE_pkg::*; (
    outClkI, outClkQ, outi, outq, vdd, vss, adcRefEn, bwTrim, 
    clkn, clkp, dcoci, dcocq, en, fClkn, fClkp, gain, inim, 
   inip, inqm, inqp, refTrim1, refTrim2, vref);

output  outClkI, outClkQ;

inout EEnet vdd, vss;

input logic adcRefEn, clkn, clkp, en, fClkn, fClkp;
input wreal4state inim, inip, inqm, inqp, vref;

output [7:0]  outi;
output [7:0]  outq;

input [7:0]  dcocq;
input [3:0]  refTrim1;
input [3:0]  gain;
input [3:0]  refTrim2;
input [3:0]  bwTrim;
input [7:0]  dcoci;

// Buses in the design

wreal4state adcInm [1:0];

wreal4state adcInp [1:0];

// wreal nets in design
wreal4state net29, net27, net28, net027, net028, net029, net030;


ADC_8bit IADC ( .outClkI(outClkI), .outClkQ(outClkQ), .fclkn(fClkn), 
    .fclkp(fClkp), .clkn(clkn), .clkp(clkp), .outi(outi), .outq(outq), 
    .ADCEn(en), .VCM(net28), .VDD(vdd), .VREF1(net29), .VREF2(net27), 
    .VSS(vss), .Vinm(adcInm), .Vinp(adcInp));

ADC_refGen IVREF ( .vdd(vdd), .vss(vss), .VCM(net28), .VREF1(net29), 
    .VREF2(net27), .en(adcRefEn), .trim1(refTrim1), .trim2(refTrim2));

dualBBA IBBA ( .dcocim(net029), .dcocip(net030), .dcocqm(net027), 
    .dcocqp(net028), .inip(inip), .gain(gain), .bwTrim(bwTrim), 
    .vss(vss), .vdd(vdd), .en(en), .outip(adcInp[0]), .inqm(inqm), 
    .inqp(inqp), .inim(inim), .outqm(adcInm[1]), .outqp(adcInp[1]), 
    .outim(adcInm[0]));

dcocDAC u_dcocQ ( .vdd(vdd), .vss(vss), .outn(net027), .outp(net028), 
    .en(en), .in(dcocq), .vref(vref));

dcocDAC u_dcocI ( .vdd(vdd), .vss(vss), .outn(net029), .outp(net030), 
    .en(en), .in(dcoci), .vref(vref));

endmodule

 // END AMS-UNL Netlist


